In [2]:
import pandas as pd
import json

In [3]:
with open('project json/t20_wc_match_results.json') as f:
    data=json.load(f)
df_match=pd.DataFrame(data[0]['matchSummary'])
df_match.head()

,team1,team2,winner,margin,ground,matchDate,scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [4]:
df_match.shape

(45, 7)

In [5]:
df_match.rename({'scorecard' : 'match_id'}, axis=1,inplace=True,)
df_match.head(5)

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [6]:
match_id_dict={}
for index,row in df_match.iterrows():
    key1= row['team1'] +  '  Vs  '   + row['team2']
    key2= row['team2'] +  '  Vs    '    + row['team1']
    match_id_dict[key1]=row["match_id"]
    match_id_dict[key2]=row["match_id"]

match_id_dict

{'Namibia  Vs  Sri Lanka': 'T20I # 1823',
 'Sri Lanka  Vs    Namibia': 'T20I # 1823',
 'Netherlands  Vs  U.A.E.': 'T20I # 1825',
 'U.A.E.  Vs    Netherlands': 'T20I # 1825',
 'Scotland  Vs  West Indies': 'T20I # 1826',
 'West Indies  Vs    Scotland': 'T20I # 1826',
 'Ireland  Vs  Zimbabwe': 'T20I # 1828',
 'Zimbabwe  Vs    Ireland': 'T20I # 1828',
 'Namibia  Vs  Netherlands': 'T20I # 1830',
 'Netherlands  Vs    Namibia': 'T20I # 1830',
 'Sri Lanka  Vs  U.A.E.': 'T20I # 1832',
 'U.A.E.  Vs    Sri Lanka': 'T20I # 1832',
 'Ireland  Vs  Scotland': 'T20I # 1833',
 'Scotland  Vs    Ireland': 'T20I # 1833',
 'West Indies  Vs  Zimbabwe': 'T20I # 1834',
 'Zimbabwe  Vs    West Indies': 'T20I # 1834',
 'Netherlands  Vs  Sri Lanka': 'T20I # 1835',
 'Sri Lanka  Vs    Netherlands': 'T20I # 1835',
 'Namibia  Vs  U.A.E.': 'T20I # 1836',
 'U.A.E.  Vs    Namibia': 'T20I # 1836',
 'Ireland  Vs  West Indies': 'T20I # 1837',
 'West Indies  Vs    Ireland': 'T20I # 1837',
 'Scotland  Vs  Zimbabwe': 'T20I # 1838',
 'Zimbabwe  Vs    Scotland': 'T20I # 1838',
 'Australia  Vs  New Zealand': 'T20I # 1839',
 'New Zealand  Vs    Australia': 'T20I # 1839',
 'Afghanistan  Vs  England': 'T20I # 1840',
 'England  Vs    Afghanistan': 'T20I # 1840',
 'Ireland  Vs  Sri Lanka': 'T20I # 1841',
 'Sri Lanka  Vs    Ireland': 'T20I # 1841',
 'India  Vs  Pakistan': 'T20I # 1842',
 'Pakistan  Vs    India': 'T20I # 1842',
 'Bangladesh  Vs  Netherlands': 'T20I # 1843',
 'Netherlands  Vs    Bangladesh': 'T20I # 1843',
 'South Africa  Vs  Zimbabwe': 'T20I # 1844',
 'Zimbabwe  Vs    South Africa': 'T20I # 1844',
 'Australia  Vs  Sri Lanka': 'T20I # 1845',
 'Sri Lanka  Vs    Australia': 'T20I # 1845',
 'England  Vs  Ireland': 'T20I # 1846',
 'Ireland  Vs    England': 'T20I # 1846',
 'Afghanistan  Vs  New Zealand': 'T20I # 1846a',
 'New Zealand  Vs    Afghanistan': 'T20I # 1846a',
 'Bangladesh  Vs  South Africa': 'T20I # 1847',
 'South Africa  Vs    Bangladesh': 'T20I # 1847',
 'India  Vs  Netherlands': 'T20I # 1848',
 'Netherlands  Vs    India': 'T20I # 1848',
 'Pakistan  Vs  Zimbabwe': 'T20I # 1849',
 'Zimbabwe  Vs    Pakistan': 'T20I # 1849',
 'Afghanistan  Vs  Ireland': 'T20I # 1849a',
 'Ireland  Vs    Afghanistan': 'T20I # 1849a',
 'Australia  Vs  England': 'T20I # 1849b',
 'England  Vs    Australia': 'T20I # 1849b',
 'New Zealand  Vs  Sri Lanka': 'T20I # 1850',
 'Sri Lanka  Vs    New Zealand': 'T20I # 1850',
 'Bangladesh  Vs  Zimbabwe': 'T20I # 1851',
 'Zimbabwe  Vs    Bangladesh': 'T20I # 1851',
 'Netherlands  Vs  Pakistan': 'T20I # 1852',
 'Pakistan  Vs    Netherlands': 'T20I # 1852',
 'India  Vs  South Africa': 'T20I # 1853',
 'South Africa  Vs    India': 'T20I # 1853',
 'Australia  Vs  Ireland': 'T20I # 1855',
 'Ireland  Vs    Australia': 'T20I # 1855',
 'Afghanistan  Vs  Sri Lanka': 'T20I # 1856',
 'Sri Lanka  Vs    Afghanistan': 'T20I # 1856',
 'England  Vs  New Zealand': 'T20I # 1858',
 'New Zealand  Vs    England': 'T20I # 1858',
 'Netherlands  Vs  Zimbabwe': 'T20I # 1859',
 'Zimbabwe  Vs    Netherlands': 'T20I # 1859',
 'Bangladesh  Vs  India': 'T20I # 1860',
 'India  Vs    Bangladesh': 'T20I # 1860',
 'Pakistan  Vs  South Africa': 'T20I # 1861',
 'South Africa  Vs    Pakistan': 'T20I # 1861',
 'Ireland  Vs  New Zealand': 'T20I # 1862',
 'New Zealand  Vs    Ireland': 'T20I # 1862',
 'Australia  Vs  Afghanistan': 'T20I # 1864',
 'Afghanistan  Vs    Australia': 'T20I # 1864',
 'England  Vs  Sri Lanka': 'T20I # 1867',
 'Sri Lanka  Vs    England': 'T20I # 1867',
 'Netherlands  Vs  South Africa': 'T20I # 1871',
 'South Africa  Vs    Netherlands': 'T20I # 1871',
 'Bangladesh  Vs  Pakistan': 'T20I # 1872',
 'Pakistan  Vs    Bangladesh': 'T20I # 1872',
 'India  Vs  Zimbabwe': 'T20I # 1873',
 'Zimbabwe  Vs    India': 'T20I # 1873',
 'New Zealand  Vs  Pakistan': 'T20I # 1877',
 'Pakistan  Vs    New Zealand': 'T20I # 1877',
 'England  Vs  India': 'T20I # 1878',
 'India  Vs    England': 'T20I # 1878',
 'England  Vs  Pakistan': 'T20I # 1879',
 'Pakistan  Vs    England': 'T20I # 1879'}

In [19]:
df_match.to_csv('project csv/dim_match_summary.csv', index=False)

In [8]:
{
    
   "Namibia Vs Sri Lanka" : "T20I # 1823",
   "Sri Lanka Vs Namibia ": "T20I # 1823",
   "Netherlands Vs U.A.E.": "T20I # 1825",
   " U.A.E.  Vs Netherlands ": "T20I # 1825",
   

}

{'Namibia Vs Sri Lanka': 'T20I # 1823',
 'Sri Lanka Vs Namibia ': 'T20I # 1823',
 'Netherlands Vs U.A.E.': 'T20I # 1825',
 ' U.A.E.  Vs Netherlands ': 'T20I # 1825'}

In [9]:
with open('project json/t20_wc_batting_summary.json') as f:
    data=json.load(f)
    all_record=[]
    for rec in data:
        all_record.extend(rec['battingSummary'])
df_battin=pd.DataFrame(all_record)
df_battin.head(5)
df_battin.tail()

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
694,Pakistan Vs England,England,3,Phil Salt,c Iftikhar Ahmed b Haris Rauf,10,9,2,0,111.11
695,Pakistan Vs England,England,4,Ben Stokes,,52,49,5,1,106.12
696,Pakistan Vs England,England,5,Harry Brook,c Shaheen Shah Afridi b Shadab Khan,20,23,1,0,86.95
697,Pakistan Vs England,England,6,Moeen Ali,b Mohammad Wasim,19,13,3,0,146.15
698,Pakistan Vs England,England,7,Liam Livingstone,,1,1,0,0,100.00

In [10]:
df_battin["out/not_out"]=df_battin.dismissal.apply(lambda x:'out' if len(x)>0 else "not_out")
df_battin.head(11)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c †Mendis b Karunaratne,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/†Mendis),44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c †Mendis b Theekshana,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis†,c †Green b Wiese,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,1,0,109.09,out

In [11]:
df_battin["mach_id"] = df_battin["match"].map(match_id_dict)
df_battin.head()

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out,mach_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out,NaN
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out,NaN
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c †Mendis b Karunaratne,20,12,1,2,166.66,out,NaN
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out,NaN
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out,NaN

In [12]:
df_battin["mach_id"] = df_battin["match"].map(lambda x: match_id_dict.get(x, 'default_value'))

In [13]:
df_battin.head()

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out,mach_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out,default_value
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out,default_value
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c †Mendis b Karunaratne,20,12,1,2,166.66,out,default_value
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out,default_value
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out,default_value

In [20]:
df_battin.to_csv('project csv/fact_batting_summary.csv',index=False)

In [14]:
with open('project json/t20_wc_bowling_summary.json') as f:
    data=json.load(f)
    all_record=[]
    for rec in data:
        all_record.extend(rec['bowlingSummary'])
all_record[:2]

[{'match': 'Namibia Vs Sri Lanka',
  'bowlingTeam': 'Sri Lanka',
  'bowlerName': 'Maheesh Theekshana',
  'overs': '4',
  'maiden': '0',
  'runs': '23',
  'wickets': '1',
  'economy': '5.75',
  '0s': '7',
  '4s': '0',
  '6s': '0',
  'wides': '2',
  'noBalls': '0'},
 {'match': 'Namibia Vs Sri Lanka',
  'bowlingTeam': 'Sri Lanka',
  'bowlerName': 'Dushmantha Chameera',
  'overs': '4',
  'maiden': '0',
  'runs': '39',
  'wickets': '1',
  'economy': '9.75',
  '0s': '6',
  '4s': '3',
  '6s': '1',
  'wides': '2',
  'noBalls': '0'}]

In [15]:
df_bowling=pd.DataFrame(all_record)
print(df_bowling.shape)
df_bowling.head()

(500, 13)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0

In [16]:
df_bowling['match_id']=df_bowling['match'].map(match_id_dict)
df_bowling.head()

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0,NaN
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0,NaN
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0,NaN
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0,NaN
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0,NaN

In [21]:
df_bowling.to_csv('project csv/fact_bowling_summary.csv',index=False)

In [22]:
df_players=pd.DataFrame(data)
print(df_players.shape)
df_players.head(10)

(45, 1)

                                      bowlingSummary
0  [{'match': 'Namibia Vs Sri Lanka', 'bowlingTea...
1  [{'match': 'U.A.E. Vs Netherlands', 'bowlingTe...
2  [{'match': 'Scotland Vs West Indies', 'bowling...
3  [{'match': 'Zimbabwe Vs Ireland', 'bowlingTeam...
4  [{'match': 'Namibia Vs Netherlands', 'bowlingT...
5  [{'match': 'Sri Lanka Vs U.A.E.', 'bowlingTeam...
6  [{'match': 'Scotland Vs Ireland', 'bowlingTeam...
7  [{'match': 'West Indies Vs Zimbabwe', 'bowling...
8  [{'match': 'Sri Lanka Vs Netherlands', 'bowlin...
9  [{'match': 'U.A.E. Vs Namibia', 'bowlingTeam':...

In [23]:
df_players[df_players['team'] == 'India']

KeyError: 'team'

In [ ]:
df_players.to_csv('project csv/dim_players_no_images.csv', index = False)

In [ ]:
df_battin.to_csv('')